#:schema https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/schema.json

source_dir = "."

extends = ["./extensions/fmt.toml", "./extensions/py.toml", "./extensions/defaults.toml"]
