#!/usr/bin/env bash
set -euo pipefail

if git --no-pager diff --staged --name-only -M -C --no-color | rg -qe '\.rs$'; then
    export NO_COLOR=1
    export CARGO_TERM_COLOR=never

    cargo clippy --all-features --fix --keep-going --allow-dirty --workspace
    cargo fmt --all --check
fi
