#:schema https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/schema.json

[pre-commit.commands.buildifier-lint-fmt]
glob        = ["*.bzl", "*.bazel"]
priority    = 0
root        = "."
run         = "buildifier -lint=fix {staged_files}"
stage_fixed = true
tags        = ["fmt"]
