#:schema https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/schema.json

no_tty = true
output = ["meta", "summary", "empty_summary", "success", "failure", "execution", "execution_out", "execution_info", "skips"]
