#:schema https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/schema.json

glob_matcher = "doublestar"
no_tty = true
output = [
  "empty_summary",
  "execution",
  "execution_info",
  "execution_out",
  "failure",
  "meta",
  "skips",
  "success",
  "summary",
]

[commit-msg.scripts."main.pl"]
args = "{1}"
runner = "perl"
tags = ["chore"]

[pre-commit]
parallel = true

[pre-commit.commands.prettier-formating]
priority = 0
run = "echo {staged_files} | xargs npx prettier --ignore-unknown --write"
stage_fixed = true
tags = ["fmt"]

[pre-commit.commands.taplo-formating]
glob = ["**/*.toml", "**/.*.toml"]
priority = 0
run = "taplo fmt {staged_files}"
stage_fixed = true
tags = ["fmt"]

[pre-commit.commands.prettier-formating.env]
NO_COLOR = "1"

[post-commit.commands.update-index]
run = "git update-index -g --verbose --refresh"
tags = ["chore"]
