#:schema https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/schema.json

[commit-msg.commands.conventional-commit]
run = "uv run --script ~/.config/git/hooks/commit_msg/commit_msg.py {1}"

[pre-commit]
parallel = true

[pre-commit.commands.prettier-formating]
priority    = 0
run         = "echo {staged_files} | xargs npx prettier --ignore-unknown --write"
stage_fixed = true

[pre-commit.commands.prettier-formating.env]
NO_COLOR = "1"

[post-commit.commands.update-index]
run = "git update-index -g --verbose --refresh"
